export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const REGISTER_COMPLETE_SUCCESS = 'REGISTER_COMPLETE_SUCCESS';
export const REGISTER_COMPLETE_REQUEST = 'REGISTER_COMPLETE_REQUEST';
export const REGISTER_COMPLETE_FAIL = 'REGISTER_COMPLETE_FAIL';

export const USER_PASSWORD_FORGOT_REQUEST = 'USER_PASSWORD_FORGOT_REQUEST';
export const USER_PASSWORD_FORGOT_SUCCESS = 'USER_PASSWORD_FORGOT_SUCCESS';
export const USER_PASSWORD_FORGOT_FAIL = 'USER_PASSWORD_FORGOT_FAIL';

export const USER_PASSWORD_RESET_REQUEST = 'USER_PASSWORD_RESET_REQUEST';
export const USER_PASSWORD_RESET_SUCCESS = 'USER_PASSWORD_RESET_SUCCESS';
export const USER_PASSWORD_RESET_FAIL = 'USER_PASSWORD_RESET_FAIL';

export const IS_SIGNED_IN = 'IS_SIGNED_IN';

export const SIGN_OUT = 'SIGN_OUT';

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';

export const PRODUCT_GET_REQUEST = 'PRODUCT_GET_REQUEST';
export const PRODUCT_GET_SUCCESS = 'PRODUCT_GET_SUCCESS';
export const PRODUCT_GET_FAIL = 'PRODUCT_GET_FAIL';

export const PRODUCT_SINGLE_GET_REQUEST = 'PRODUCT_SINGLE_GET_REQUEST';
export const PRODUCT_SINGLE_GET_SUCCESS = 'PRODUCT_SINGLE_GET_SUCCESS';
export const PRODUCT_SINGLE_GET_FAIL = 'PRODUCT_SINGLE_GET_FAIL';

export const PRODUCT_RELATED_GET_REQUEST = 'PRODUCT_RELATED_GET_REQUEST';
export const PRODUCT_RELATED_GET_SUCCESS = 'PRODUCT_RELATED_GET_SUCCESS';
export const PRODUCT_RELATED_GET_FAIL = 'PRODUCT_RELATED_GET_FAIL';

export const PRODUCT_AUTHOR_GET_REQUEST = 'PRODUCT_AUTHOR_GET_REQUEST';
export const PRODUCT_AUTHOR_GET_SUCCESS = 'PRODUCT_AUTHOR_GET_SUCCESS';
export const PRODUCT_AUTHOR_GET_FAIL = 'PRODUCT_AUTHOR_GET_FAIL';

export const PRODUCT_USER_GET_REQUEST = 'PRODUCT_USER_GET_REQUEST';
export const PRODUCT_USER_GET_SUCCESS = 'PRODUCT_USER_GET_SUCCESS';
export const PRODUCT_USER_GET_FAIL = 'PRODUCT_USER_GET_FAIL';

export const FIND_CATEGORIES_REQUEST = 'FIND_CATEGORIES_REQUEST';
export const FIND_CATEGORIES_SUCCESS = 'FIND_CATEGORIES_SUCCESS';
export const FIND_CATEGORIES_FAIL = 'FIND_CATEGORIES_FAIL';

export const FIND_SUB_CATEGORIES_REQUEST = 'FIND_SUB_CATEGORIES_REQUEST';
export const FIND_SUB_CATEGORIES_SUCCESS = 'FIND_SUB_CATEGORIES_SUCCESS';
export const FIND_SUB_CATEGORIES_FAIL = 'FIND_SUB_CATEGORIES_FAIL';

export const FIND_SUPER_SUB_CATEGORIES_REQUEST =
  'FIND_SUPER_SUB_CATEGORIES_REQUEST';
export const FIND_SUPER_SUB_CATEGORIES_SUCCESS =
  'FIND_SUPER_SUB_CATEGORIES_SUCCESS';
export const FIND_SUPER_SUB_CATEGORIES_FAIL = 'FIND_SUPER_SUB_CATEGORIES_FAIL';

export const UPLOAD_IMAGES_REQUEST = 'UPLOAD_IMAGES_REQUEST';
export const UPLOAD_IMAGES_SUCCESS = 'UPLOAD_IMAGES_SUCCESS';
export const UPLOAD_IMAGES_FAIL = 'UPLOAD_IMAGES_FAIL';

export const REMOVE_IMAGES_REQUEST = 'REMOVE_IMAGES_REQUEST';
export const REMOVE_IMAGES_SUCCESS = 'REMOVE_IMAGES_SUCCESS';
export const REMOVE_IMAGES_FAIL = 'REMOVE_IMAGES_FAIL';
